version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    environment:
      POSTGRES_DB: your_db_name # Замените на имя вашей БД
      POSTGRES_USER: your_db_user # Замените на имя пользователя
      POSTGRES_PASSWORD: your_db_password # Замените на пароль
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local_network

  qdrant:
    image: qdrant/qdrant:v1.7.4 # Рекомендуется использовать конкретную версию
    container_name: local-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local_network

# (Опционально) Можно добавить сервис для вашего Node.js приложения здесь,
# чтобы запускать все вместе, но для начала достаточно баз данных.
# app:
#   build:
#     context: .
#     dockerfile: Dockerfile
#   container_name: local-app
#   depends_on:
#     - postgres
#     - qdrant
#   ports:
#     - "3000:3000" # Пример порта, замените на ваш
#   environment:
#     # Переменные окружения для подключения к БД и Qdrant из .env
#     SUPABASE_URL: http://local-postgres:5432 # Пример, уточните по Supabase
#     SUPABASE_ANON_KEY: your_anon_key # Пример
#     QDRANT_URL: http://local-qdrant:6333
#     # ... другие переменные ...
#   networks:
#     - local_network

volumes:
  postgres_data:
  qdrant_data:

networks:
  local_network:
    driver: bridge 